# Используем Go Alpine
FROM golang:1.25.1-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Запуск тестов по умолчанию
CMD ["go", "test", "-v", "./tests/integration_tests/..."]
