FROM golang:1.25.1-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Копируем весь код (включая tests)
COPY . .

# Запускаем тесты внутри контейнера
CMD ["go", "test", "-v", "./tests/..."]
